version: "3.9"

services:
  cf-backend:
    build:
      dockerfile: ./Dockerfiles/api.dockerfile
      context: .
    container_name: cf-backend
    env_file:
      - .env
    depends_on:
      - cf-db
    ports:
      - "8000:8000"

  cf-db:
    image: postgres:15.0
    container_name: cf-db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

  cf-test:
    build:
      dockerfile: ./Dockerfiles/test.dockerfile
      context: .
    container_name: cf-test
    env_file:
      - .env
    depends_on:
      - cf-db
      - cf-backend